
default: &default
  adapter: mysql2
  encoding: utf8
  pool: 5
  username: root
  password:	'tortola1234'
  #socket: /var/lib/mysql/mysql.sock
  socket: /var/run/mysqld/mysqld.sock

development:
  <<: *default
  database: Organimaq_development

test:
  <<: *default
  database: Organimaq_test

#
production:
  <<: *default
  database: Organimaq_production
  username: Organimaq
  password: <%= ENV['ORGANIMAQ_DATABASE_PASSWORD'] %>
